### ISSUE TITLE
Basin Analysis Report - Packing Reports

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#11]
There are two reports to be generated:

**Watershed Characteristics Report**

- Cover sheet / summary page (add report name above the AOI name): Basic AOI and report information, station location stats, station representation stats, annual run-off ratio, data sources (remove the data source entries that are only used in the site analysis), credits (change Maps and charts to Report)
- AOI terrain characteristics: Elevation, slope, aspect (maps & charts), existing stations represented areas
- AOI precipitation characteristics: Precipitation distribution, elev-precip correlation chart, precip contributing area map, SWE maps, SWE delta maps, existing station locations, area-elevation/precip/station distribution charts and tables, critical precip zones (map & table), seasonal (winter) precip & precip % maps

**Site Analysis Report (add a check box to make this report optional - default value is checked)**

- Cover sheet / summary page (add report name above the AOI name): Basic AOI and report information, station location stats, station representation stats, annual run-off ratio, data sources, credits
- Proximity to access road, public (non-wilderness land), land ownership, area below treeline, Potential site locations

**Comment by jdduh** [comment]
Summary of changes to the existing cover sheet:

- add report name above the AOI name (for the cover sheets of both reports)
- remove the data source entries that are only used in the site analysis from the Watershed Characteristics report
- change the "Maps and charts" to "Report" on the first line of the end credit paragraph

**Comment by lbross** [comment]
The title page for the two reports are identical except for:
1. The new report name(s)
2. The list of data source entries

Question: The title page text for the existing sites section have references to the REPRESENTATION maps that will not be in the Site Analysis report. How would you like to handle this?

Question: What is 'existing station locations'? We don't have a map just for this. They are on some of the other maps. What is area-elevation/precip/station distribution tables? We have charts.

It looks like you want to reorder some of the pages. Is the listing below correct? 
Pages (in order) for the Watershed Characteristics Report
1. Summary page
2. Elevation Distribution
3. Aspect Distribution
4. Slope Distribution
5. Aspect Chart
6. Slope Chart
7. Snotel Sites Representation
8. Snow Course Sites Representation
9. Combined Sites Representation
10. Precipitation Distribution
11. Elevation-Precipitation Correlation Chart
12. Precipitation Contribution map (new)
13. SWE Maps (Nov - Jul)
14. SWE Delta Maps (Nov/Dec - Jun/Jul) (new)
15. Elevation Precipitation Site Distribution Chart (% by elevation area)
16. Elevation Precipitation Site Distribution Chart (Cumulative Precipitation)
17. Critical Precipitation Zones Map
18. Critical Precipitation Zones Table
19. Seasonal Precipitation Maps (new)
20. % of annual precipitation Seasonal Precipitation Maps (new)

Maps (in order) for the Site Analysis Report:
1. Proximity to access road
2. Public (non-wilderness land)
3. Land ownership
4. Area below treeline
5. Potential site locations

**Comment by lbross** [comment]
The file names for the packaged reports are site_analysis_report.pdf and watershed_report.pdf. I uploaded samples to basins in the /BAGIS/BAGIS Reports directory. These samples do not include the precipitation contribution map or the seasonal precipitation map as these maps are still in development. Please review and let me know of any changes.

**Comment by lbross** [comment]
Change document titles. Replace aoi_name with stationName from pourpoint layer as prefix. Replace spaces with underscores before using.

**Comment by lbross** [comment]
Change document titles. Replace stationName from pourpoint layer with nwccname from master_aoi_list.csv stored on AGOL. Use the station triplet from the pourpoint layer to look up the record in the .csv file (same link as retrieving annual runoff value). Replace spaces with underscores before using. Map and chart titles need to use this value too.

**Comment by lbross** [comment]
AGOL has the option of uploading a .csv with lat/long as a feature service. Having this data in a feature service rather than a CSV will be easier to work with in BAGIS-PRO. I uploaded a copy as a feature service and will be moving forward with this approach. If this is a bad idea, please let me know.

**Comment by lbross** [comment]
I updated the setAoi function to find the stationtriplet and query for the nwccname. It takes a little longer to set the AOI, but with this approach all of the tools have access to the nwccname after the AOI is set

**Comment by jdduh** [comment]
As of today, NWCC decides to publish the whole report as one pdf file (and the separate pages), instead of two reports. This is related to the recent development in USDA research priority. Snowpack survey/monitoring network (i.e., SNOTEL) analysis and siting become more important.

**Comment by lbross** [comment]
I changed the watershed report to no longer exclude the site analysis maps and we no longer create the site analysis report separately. I left the code in place in case they change their minds and want to go back the other way. I published 2 new examples of the watershed report to the NRCS portal and removed the site analysis reports. This includes the fix from Friday to remove the duplicate roads layer from the legend

**Comment by jdduh** [comment]
Here is the final ordering of the maps, charts, and tables. The blank lines separating the items indicate the grouping of "individual" maps.

Summary
Basin Location Map
Active Sites Table

Elevation Distribution Map

Aspect Distribution Map
Aspect Distribution Chart

Slope Distribution Map
Slope Distribution Chart

SNOTEL Sites Representation Map
Snow Course Sites Representation Map
SNOTEL & Snow Course Combined Sites Representation Map

Precipitation Distribution Map
Elevation-Precipitation Correlation Chart
Subbasin Annual Precipitation Contribution Map
Area-Elevation, Precipitation, & Site Distribution Chart (% By Elevation Area)
Area-Elevation, Precipitation, & Site Distribution Chart (Cumulative % Precipitation By Elevation Area)
Critical Precipitation Zones Map
Critical Precipitation Zones Table

Winter (Nov-Mar) Precipitation Map
Seasonal Precipitation Contribution: Dec, Jan, & Feb Map
Seasonal Precipitation Contribution: Mar, Apr, & May Map
Seasonal Precipitation Contribution: Jun, Jul, & Aug Map
Seasonal Precipitation Contribution: Sep, Oct, & Nov Map

SNODAS SWE Nov 1ST Map
SNODAS SWE Dec 1ST Map
SNODAS SWE Jan 1ST Map
SNODAS SWE Feb 1ST Map
SNODAS SWE Mar 1ST Map
SNODAS SWE Apr 1ST Map
SNODAS SWE May 1ST Map
SNODAS SWE Jun 1ST Map
SNODAS SWE Jul 1ST Map
Average November SWE Delta Map
Average December SWE Delta Map
Average January SWE Delta Map
Average February SWE Delta Map
Average March SWE Delta Map
Average April SWE Delta Map

Proximity to Access Road Map
Federal Non-Wilderness Land Map
Public Land Ownership Map
Area Below Treeline Map
Potential Site Locations on Elevation Zones Map
Potential Site Locations on Precipitation Zones Map
Potential Site Locations on Subbasin Precipitation Contribution Map

**Comment by jdduh** [comment]
Please see if the file names (in bold) make sense. 
All combined maps, charts, and tables -> **AOI_Name + " Watershed Report"**

**AOI_Name + " Overview"**
Summary
Basin Location Map
Active Sites Table

**AOI_Name + " Elevation Distribution"**
Elevation Distribution Map

**AOI_Name + " Aspect Distribution"**
Aspect Distribution Map
Aspect Distribution Chart

**AOI_Name + " Slope Distribution"**
Slope Distribution Map
Slope Distribution Chart

**AOI_Name + " Site Representation"**
SNOTEL Sites Representation Map
Snow Course Sites Representation Map
SNOTEL & Snow Course Combined Sites Representation Map

**AOI_Name + " Precipitation Distribution"**
Precipitation Distribution Map
Elevation-Precipitation Correlation Chart
Subbasin Annual Precipitation Contribution Map
Area-Elevation, Precipitation, & Site Distribution Chart (% By Elevation Area)
Area-Elevation, Precipitation, & Site Distribution Chart (Cumulative % Precipitation By Elevation Area)
Critical Precipitation Zones Map
Critical Precipitation Zones Table

**AOI_Name + " Seasonal Precipitation Distribution"**
Winter (Nov-Mar) Precipitation Map
Seasonal Precipitation Contribution: Dec, Jan, & Feb Map
Seasonal Precipitation Contribution: Mar, Apr, & May Map
Seasonal Precipitation Contribution: Jun, Jul, & Aug Map
Seasonal Precipitation Contribution: Sep, Oct, & Nov Map

**AOI_Name + " SNODAS SWE"**
SNODAS SWE Nov 1ST Map
SNODAS SWE Dec 1ST Map
SNODAS SWE Jan 1ST Map
SNODAS SWE Feb 1ST Map
SNODAS SWE Mar 1ST Map
SNODAS SWE Apr 1ST Map
SNODAS SWE May 1ST Map
SNODAS SWE Jun 1ST Map
SNODAS SWE Jul 1ST Map
Average November SWE Delta Map
Average December SWE Delta Map
Average January SWE Delta Map
Average February SWE Delta Map
Average March SWE Delta Map
Average April SWE Delta Map
Average May SWE Delta Map
Average Jun SWE Delta Map

**AOI_Name + " Potential Site Analysis"**
Proximity to Access Road Map
Federal Non-Wilderness Land Map
Public Land Ownership Map
Area Below Treeline Map
Potential Site Locations on Elevation Zones Map
Potential Site Locations on Precipitation Zones Map
Potential Site Locations on Subbasin Precipitation Contribution Map

**Comment by lbross** [comment]
Can you take a look and see if I got it right? If not, please make the adjustment on the spreadsheet and repost. And please tell me which charts are affected. Thanks!
[yampa_pro.xlsx](https://github.com/PSU-CSAR/bagis-pro/files/7355115/yampa_pro.xlsx)

**Comment by lbross** [comment]
Re-order " Potential Site Analysis" group as follows:

Potential Site Locations on Elevation Zones Map
Potential Site Locations on Precipitation Zones Map
Potential Site Locations on Subbasin Precipitation Contribution Map
Proximity to Access Road Map
Federal Non-Wilderness Land Map
Public Land Ownership Map (Why is this missing?)
Area Below Treeline Map

**Comment by lbross** [comment]
Add new section after Elevation Distribution Map
AOI_Name + " Land Cover"
Land Cover Map

**Comment by jdduh** [comment]
Just to tidy up the spec for the AOI_Name + " Potential Site Analysis" section.

- Potential Site Locations on Elevation Zones Map
- Potential Site Locations on Precipitation Zones Map
- Potential Site Locations on Subbasin Precipitation Contribution Map
- Proximity to Access Road Map
- Land Ownership Map (formerly Federal Non-Wilderness Land Map - the backend data will be updated to include Indian Reservation data, only need to change the map title). There is an ongoing discussion if the Indian Reservation areas are included as potential site locations, currently not.
- Remove Public Land Ownership Map (this map is considered as redundant to the Land Ownership map)
- Forested Land (formerly Area Below Treeline Map - to be replaced by NLCD forested land)

**Comment by jdduh** [comment]
NWCC has confirmed to include Indian Reservation areas as potential site locations. We will need to update the spec for #9 issue.

**Comment by jdduh** [comment]
New spec for packing the report. This is also related to #12.
1. No need to generate separate pdf files. NWCC only needs the complete Watershed Report file.
2. The pdf file will use the station triplet ID as the file name, e.g., : 06228000_WY_USGS_Watershed-Report.pdf. Please use URL-safe characters whenever possible. Use underscores as the delimiter and dash as "space".
3. NWCC plans to use hashtags to point to specific pages in the pdf, which means all reports must have the same number of pages. We will need to replace missing maps/tables/charts with blank or padding pages so that pages in all the pdf files align.

**Comment by lbross** [comment]
Please take a look at [this map](https://nrcs.maps.arcgis.com/sharing/rest/content/items/3bac4edeba8a438b9e1a2a8034edfac0/data) on the Portal. The file was too big to upload to GitHub. This is a sample where I disabled the chart creation so it would complete faster for debugging. It also gives you an example of the padding pages. The padding page is just a Word document converted to pdf and packaged with the add-in. So if you would like some different text or font, you can send a new Word document.

**Comment by jdduh** [comment]
So the text is not customizable for individual missing pages? We need to provide additional descriptions to explain why the page is blank. Probably add something like: "THIS PAGE INTENTIONALY LEFT BLANK There is no data to create the

**Comment by jdduh** [comment]
We can add a TOC page (on the 3rd page, behind the Data sources page) that shows the page numbers and page titles.

**Comment by lbross** [comment]
To be customizable, we would need to implement the process we use for the title and sites pages. This means creating an html page from an xsl template and converting that to pdf before including it in the complete pdf document. We could probably get by with one xsl template if we created it so we could fill-in the variable information on the template. But it would still have to be generated for each missing page each time the report is generated.

A second alternative would be to package 29 filler pages with the add-in that are created by the Word to PDF conversion that I used in the sample. This would be easy to manage using arrays. Or maybe we could cut it down to two, map vs chart?

Do you have a sample of the format you would like for the TOC?

**Comment by jdduh** [comment]
Is missing SNOTEL/Snow Course sites the only possibility that would lead to blank/missing pages? Let's plan to use just one blank padding sheet for now. 

As to the TOC, I know that it's difficult to add page numbers to the report. If each map/chart/table will appear in a fixed sequence (without any gap), then maybe we can add a number to the page (map/chart) title so that the TOC is easier to use. We probably also can use the same numbers when designing the BAGIS Pro GUI. If we take this route, then the TOC will be just the page title, something like:

Table of Contents
1.  LOCATION MAP
2. Active Sites in [Station_Name]
3. Elevation Distribution
4. Land Cover
5. ...

**Comment by lbross** [comment]
Please see attached for sample of map (chart) specific placeholder pages. I need to center the text. Any other requests?
![blank_page](https://user-images.githubusercontent.com/11527966/159810137-445d88a2-5ee1-40a9-bcd1-fe6cf7cd89a9.jpg)

**Comment by jdduh** [comment]
Looks good. Yes, please center the text.

**Comment by lbross** [comment]
The sample on the portal for 09361500_CO_USGS includes 3 example filler pages for review. This is done.
