### ISSUE TITLE
Basin Analysis Report - Potential Site Locations

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#19]
In addition to the original map showing the locations on the Elevation zones background, add two new "Potential Site Locations" maps: one with the "ANNUAL PRECIPITATION DISTRIBUTION" map as the background, the other with the "SUBBASIN ANNUAL PRECIPITATION CONTRIBUTION" as the background. We can keep the same map title for all three maps, but keep (add) the background layer name to the legend. These layers are: Elevation Zones, Precipitation Zones, and Precipitation Contribution.

**Comment by lbross** [comment]
This is done. Uploaded new sample watershed reports for Elwha and Elk rivers to portal.
