### ISSUE TITLE
Basin Analysis Report - AOI Reference Location Map

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#22]
Add a location map after the summary page to show:
- AOI boundary
- Western state boundaries
- BAGIS Reference Maps.lyr (with the BAGIS AOIs and HUC6 watersheds layer turned off)

Zoom the map to the extend of the western state boundaries.
Map title: 
LOCATION MAP
AOI Name

I will either create a new map service for the wester state boundaries or add the boundary layer to the BAGIS reference map.

**Comment by jdduh** [comment]
http://webservices.geog.pdx.edu/arcgis/rest/services/BAGIS_GISLayers/AOI_Location_Maps/MapServer
Alternatively, we can create a .lyr file for direct access of the webmap.

**Comment by lbross** [comment]
Make AOI boundary a solid red color. Extent should be the same as the web service initially. Between summary page and sites table

**Comment by lbross** [comment]
Seeking clarification on the layers that should be in this map. The western state boundaries and AOI boundary are a given. Do you also want to include the Major Rivers and Terrain Layers from the BAGIS Reference Maps.lyr? I'm having trouble changing the extent on the map frame in Pro, but the Major Rivers layer doesn't look so good at the western states extent. It overwhelms most of the other detail on the map. I will paste a sample when I can figure out the extent.

**Comment by jdduh** [comment]
Please use the AOI_Location_Map webmap as the background. It looks something like this. I put several AOIs outlines on the maps. Most AOIs are fine with a 1pt red outline, except for Santa_Fe_R_nr_Santa_Fe (in NM).

![image](https://user-images.githubusercontent.com/11510708/134593608-9b43f9dc-1bdc-406f-8050-62461006ec89.png)

**Comment by jdduh** [comment]
Now everything in 3pt outline.

![image](https://user-images.githubusercontent.com/11510708/134593790-786d38f1-59a2-464b-8106-93eefb71ff72.png)

**Comment by jdduh** [comment]
Here is an example with a large AOI with a 3pt outline.

![image](https://user-images.githubusercontent.com/11510708/134594341-5a5c867f-40b9-47b8-9a4e-5eef88c0e03a.png)

**Comment by jdduh** [comment]
Here is Santa Fe R all by itself with a 3pt outline.
![image](https://user-images.githubusercontent.com/11510708/134594473-93d06b3c-bffb-406a-9f47-4c589b208858.png)

**Comment by jdduh** [comment]
Santa Fe R again, with a 1pt outline. We should go with the 3pt outline.

![image](https://user-images.githubusercontent.com/11510708/134594587-81c73a61-2939-4095-b620-efe05dfbe1f2.png)

**Comment by jdduh** [comment]
Large AOI without fill. I prefer the solid red (with a 3pt outline).

![image](https://user-images.githubusercontent.com/11510708/134594693-16712fdc-cc5c-4f23-9f98-d519e10963f8.png)

**Comment by lbross** [comment]
See attached sample for animas. I had some trouble including this map on the same map frame as all the others due to the different extent. It took too long for Pro to redraw the extent to have the map ready for the export. As a workaround a created an additional map and layout. This meant redoing some of my initial work, but it works more smoothly. Let me know if you have any corrections.
[Animas_R_at_Durango_map_aoi_location.pdf](https://github.com/PSU-CSAR/bagis-pro/files/7247546/Animas_R_at_Durango_map_aoi_location.pdf)

**Comment by jdduh** [comment]
Looks good. Something wrong with the imperial unit on the scale bar. Can you also add a legend to the map?

**Comment by lbross** [comment]
Do you want all of the layers names in the legend? AOI Boundary, State Boundaries, Major Rivers, and HUC6 watersheds? I have no idea what is going on with the scale bar. It looks fine in interactive mode :-(

**Comment by jdduh** [comment]
We could add all the layer names in the legend. Let me know if that's an issue. The state boundaries and major rivers are self-explanatory, but AOI and HUC6 must be in the legend.

**Comment by lbross** [comment]
It's easier to have all the layer names than selected layer names, so I will do that for now. However, I know how to remove those that we don't want, so if you just want to show selected let me know.

**Comment by lbross** [comment]
How is this? It took me a while to fix the problem with the scale bar. It had something to do with the order items were added and if they were called on the GUI or background thread. Finally got there though and fixed some other things along the way.
[Location Map 1.pdf](https://github.com/PSU-CSAR/bagis-pro/files/7261750/Location.Map.1.pdf)

**Comment by jdduh** [comment]
Looks great! Thanks! This map goes after the summary page.
