### ISSUE TITLE
Stranger asking for Help

### ISSUE THREAD

**Issue by Chapin2018** [PSU-CSAR/bagis-pro#23]
@lbross Lesley
hello
I am a stranger from China and I am learning ArcGIS Pro recently.
I saw your project in the learning process, could you please give me your contact information? I hope to get some guidance on ArcGIS Pro development from you, because ArcGIS Pro has little information in China.
I can't find your contact information on Github, so I can only post this offensive question on issues.
Say sorry in advance and I will delete this question soon if I don't get a reply.
Looking forward to your reply!

**Comment by lbross** [comment]
@Chapin2018. I am happy to answer any ArcGIS Pro SDK questions you may have. I get most of my answers from the [ESRI ArcGIS Pro community](https://community.esri.com/t5/arcgis-pro-sdk/ct-p/arcgis-pro-sdk). Also the [esri sample projects](https://github.com/Esri/arcgis-pro-sdk-community-samples) in GitHub are helpful. 

If you want to post your e-mail address on this issue, I will send you mine directly. I'm not sure how to find your e-mail address on GitHub.
