### ISSUE TITLE
Basin Analysis Report - AOIs

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#24]
NWCC has identified 17 AOIs for the first batch of reports. The AOIs are assembled on CS3 at C:\AOIs\BasinAnalysisReport_AOIs. All theses AOIs are still in Weasel data format. We can start testing the ArcGIS Pro batch tool on these AOIs and upload the reports to ArcGIS Hub for further reviews. Here is a list of these AOIs.

- Cut Bank Ck nr Browning	06098500:MT:USGS
- Yellowstone R at Corwin Springs	06191500:MT:USGS
- Wind R at Riverton	06228000:WY:USGS
- Little Bighorn R nr Hardin	06294000:MT:USGS
- Rio Chama bl El Vado Dam	08285500:NM:USGS
- Tomichi Ck at Gunnison	09119000:CO:USGS
- Yampa R nr Maybell	09251000:CO:USGS
- Animas R at Durango	09361500:CO:USGS
- Salt R nr Roosevelt	09498500:AZ:USGS
- Sevier R nr Gunnison	10217000:UT:USGS
- EF Carson R nr Gardnerville	10309000:NV:USGS
- Humboldt R nr Elko	10318500:NV:USGS
- Truckee R at Farad	10346000:CA:USGS
- Tobacco R nr Eureka	12301300:MT:USGS
- Boise R nr Boise	13202000:ID:USGS
- Deschutes R at Benham Falls	14064500:OR:USGS
- Cowlitz R bl Mayfield	14238000:WA:USGS

**Comment by jdduh** [comment]
Some minor updates of the list. AOIs on CS3 were also updated. These AOIs are being converted to GDB format.

- Marias R nr Shelby	06099500:MT:USGS
- Yellowstone R at Corwin Springs	06191500:MT:USGS
- Wind R at Riverton	06228000:WY:USGS
- Little Bighorn R nr Hardin	06294000:MT:USGS
- El Vado Reservoir Inflow	08285500:NM:USGS
- Tomichi Ck at Gunnison	09119000:CO:USGS
- Yampa R nr Maybell	09251000:CO:USGS
- Animas R at Durango	09361500:CO:USGS
- Salt R nr Roosevelt	09498500:AZ:USGS
- Sevier R nr Gunnison	10217000:UT:USGS
- EF Calrson R nr Gardnerville	10309000:NV:USGS
- Humboldt R nr Elko	10318500:NV:USGS
- Truckee R at Farad	10346000:CA:USGS
- Tobacco R nr Eureka	12301300:MT:USGS
- Boise R nr Boise	13202000:ID:USGS
- Deschutes R at Benham Falls	14064500:OR:USGS
- Cowlitz R bl Mayfiled	14238000:WA:USGS

**Comment by lbross** [comment]
Add button to Batch PDF Export tool to rename AOI folders that the tool finds with the NWCC AOI name but with spaces instead of underscores. We will ignore the date for now because the clipping date for all the layers is recorded in the analysis.xml file.
