### ISSUE TITLE
Add new waterbodies layer to all maps

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/bagis-pro#26]
Gus suggests using NLCD2019. @jdduh will need to add this as a webservice so that it can be clipped. Gus also asked for a land cover map to use for general background information. Need all requirements for this map: title, symbology, which map group should it be added to? Should the waterbodies layer appear on the legends?

Edited: Does Gus' land cover map replace the 'AREA BELOW TREELINE' map? Gus' comments on the 'AREA BELOW TREELINE' map: I recommend we go for a simpler solution here and create a new "forested" layer derived from the NLCD2019 dataset.  This would include deciduous forest, evergreen forest, and mixed forest classifications.  However, rather than showing a "forested" map, show a NLCD2019 map for the basin.

**Comment by lbross** [comment]
URL for new Land Cover map: http://webservices.geog.pdx.edu/arcgis/rest/services/BAGIS_Databin/NLCD_2019_land_cover/ImageServer).
See issue #28 for symbology of new map. Do we want to add this as waterbodies to other maps?

**Comment by jdduh** [comment]
Yes, please create a separate NLCD land cover layer that shows only water features (code = 11) and add it to all maps. Use the same blue color as the AOI stream layer and just show the NLCD symbol (labeled as "water bodies") in the legend.

I have republished the land cover image service. The 3 band issue was caused by that the image has a "colormap" defined. After deleting the colormap and republishing the service, the image service has only one band.

**Comment by lbross** [comment]
Lesley to create 2 .lyrx files for land cover map and the water bodies layer. Test downloading to BAGIS-PRO via FTP. If that doesn't work, distribute files with add-in.

**Comment by lbross** [comment]
Should the legend for the waterbodies layer be 'Waterbodies' or 'Open Water'. On the NLCD layer, that classification is labeled 'Open Water'. I am using the SetNull tool to set all of the cells to null that aren't 11. I will need to add a name column to that output that can be displayed in the legend.

**Comment by jdduh** [comment]
We will use that entry to represent both open water and streams. Let's called it waterbodies, unless you think open water is a better way to capture both. We could also call it just "water" or "open water & streams"

**Comment by lbross** [comment]
Should we add the waterbodies vector to the land cover map? It seems that the symbology of the land cover map should cover the open water pixels.
