### ISSUE TITLE
Basin Analysis Report - Maps without the contents caused by clipping layers to map

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#31]
Sevier R nr Gunnison 10217000:UT:USGS Maps without the contents (see attached screenshots). The maps with multiple mapframes do show up fine. This AOI boundary has more than 20,000 vertices which resulted in an ArcGIS Pro warning saying that "Performance may be impacted when clipping to a shape with more than 20,000 vertices." This might be a problem with Pro not refreshing the display fast enough that the map is ready for the PDF export. One workaround is by setting the AOI and using the export map package to pdf button to genereate the report. It's much faster than the batch export process.

![image](https://user-images.githubusercontent.com/11510708/164092360-52da3c1b-7866-4fe6-b991-73b4124847ba.png)

**Comment by jdduh** [comment]
Quoting Lesley.

For the Sevier R nr Gunnison AOI I needed to set the tolerance to 50 meters to get the vertices count below 20,000. There is a sample watershed report called Sevier R nr Gunnison 10217000_UT_USGS_Watershed-Report-Wang.pdf generated using this tolerance. I can't tell the difference between this report and the original report. Interestingly, the report size is noticeably smaller.

I also tested 50 meters for animas_r_at_durango_09102010, a relatively small AOI, and could not see the difference in the report.

Then I found a method in the API where I can query the pointCount of the aoi_v polygon, which I assume is the vertices count. For Animas, without simplification, this was only about 4800. What do you think about querying the pointCount of aoi_v before setting the ClipGeometry? For smaller AOIs it would already be < 20000 so we would just use the standard aoi_v polygon. For larger aois, we could run an iteration where we simplify by 20 or 30 or ? meters each pass until the pointCount drops below 20000, at which time we will use that polygon for the clipping geometry. We could choose an even lower pointCount if you want.

**Comment by jdduh** [comment]
The API approach sounds good. We might be able to perform a more aggressive polygon simplification (e.g., by setting the tolerance to, say, 300 meters).  I will identify an even larger AOI to test if the blank map was indeed caused by the clipping setting. Once confirmed, then we can implement the simplification routine in the batch tool.

**Comment by jdduh** [comment]
I have two AOIs that are experiencing this issue.  The first one is RIO GRANDE NR LOBATOS (08251500_CO_USGS_Watershed-Report). When I ran the batch tool on this AOI only, it crashed ArcGIS Pro. This AOI can be accessed at ftp://basins.geog.pdx.edu/BAGIS/BAGIS_aois/.

The second AOI is Sevier R nr Gunnison (10217000_UT_USGS_Watershed-Report). Let me know if any files from this AOI are needed.

![image](https://user-images.githubusercontent.com/11510708/183976850-84ee3e65-3bf3-47e7-a69e-916b8c4e891d.png)

**Comment by lbross** [comment]
I don't have an answer for the missing contents. I can look into the crashing after the ArcGIS license issue is resolved on basins. There are many dependencies on basins and its web services in the batch tool.

**Comment by lbross** [comment]
I was able to run the batch tool for RIO GRANDE NR LOBATOS on CS3 after basins/bagis came back online with no errors. I examined the PDF document that was created and all of the contents are visible. (C:\AOIs\Debug\rio_grande_nr_lobatos_obs_usgs_09132010\maps_publish) I can confirm that I see the warning message about performance and clipping to a shape with > 20,000 vertices with this AOI. This may be a function of how many resources the client computer has?

**Comment by lbross** [comment]
I'm not sure why this wouldn't work on your desktop computer. Those 2 map tabs should be in place. They are the source for the layouts. We also create map tabs for each of the maps on the multi-map pages, but we close them after the layout tabs load so there aren't so many tabs open. Is your desktop computer running the same version of ArcGIS Pro as CS3? (Please don't upgrade CS3 until we determine this is the issue).
There should be a detailed log on the 'logs' folder at the AOI root. Perhaps this will provide some insight? You can also try setting the AOI on the BAGIS toolbar and clicking the load maps button to see what happens.
