### ISSUE TITLE
BAGIS Pro addin versions

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#41]
Please update the addin's version text. This is very likely to be the final release for ArcGIS Pro 2.X.

Date: 01/01/2023
Target Version: 2.9

![image](https://user-images.githubusercontent.com/11510708/212495709-7d9a49d8-f1a0-4033-82b3-20edbcd4fec2.png)

**Comment by lbross** [comment]
Do you want to wait until we get the Alaska support in? issue #40. Or I can do it this week.

**Comment by jdduh** [comment]
Let's wait until the Alaska support is implemented.

**Comment by lbross** [comment]
Well... this didn't go quite as planned for a variety of reasons, but I wanted to make sure the Target Version was set as you requested. The date was already updated on the most recent build. There is a new version of this AddIn on basins.
