### ISSUE TITLE
Basin Analysis Report - Annual runoff ratio

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#5]
Generate an annual runoff ratio using annual PRISM volume and annual streamflow runoff. 
Each AOI has one value.
Annual_Runoff_Ratio = Annual_Precip / Annual_streamflow_acre-foot * 100%
NWCC provides the 1981-2010 annual streamflow data (.CSV). Possible getting 1991-2020 data (need matching PRISM 30-year normals).

- Use stationtriplet as the ID for matching
- AOI's Annual_Precip value is generated in the "Precipitation Representation Table."
- Host the .CSV file on a server so that the batch tool is more portable
- The streamflow volume is stored in '1981_2010_Average_kac_ft' column, consider renaming it so that future data update won't involve a recompilation of the add-ins.
- Attached is the .CSV file. I added the .txt file extension name so that it can be uploaded to GitHub.

[1981_2010_annual_runoff_averages.csv.txt](https://github.com/PSU-CSAR/bagis-pro/files/6092654/1981_2010_annual_runoff_averages.csv.txt)

**Comment by lbross** [comment]
Are we adding this value as a line on the title page? Is the AOI's Annual_Precip value the sum of the vol_acre_ft column on the "Precipitation Representation Table." ?

**Comment by lbross** [comment]
The ID column values have a trailing ":". Will this be true on the final .csv file? What do we print on the title page if the gauge station is either missing from the data set or if the value is null? I found a way to open a .csv file as a dataset so that it can be handled much like a database.

**Comment by jdduh** [comment]
I added the colon to the ID so that I can create the triplet ID that is to be used for matching the AOI. NWCC only provides the ID and non-abbrev state names. All stations are managed by USGS. We have to create the station triplet ID ourselves if NWCC provides a new streamflow file. How about putting 'No stream flow data' for the AOIs that don't have a matching USGS gauge station?

**Comment by lbross** [comment]
I have successfully retrieved the streamflow information from a .csv file stored in the NRCS Portal. If a new streamflow file is provided, we will need to modify it:
- The header for the column containing the triplet ID must be called 'stationtriplet'. The value of the stationtriplet should be in this format: 15493000:AK:USGS
- The header for the column containing the runoff value must be called 'Average_kac_ft'
- Rename the file to 'annual_runoff_averages.csv' and use the NRCS Portal web interface to 'Update' the current annual_runoff_averages document. ArcGIS Pro uses the item id to search for the document so this needs to remain the same with a new version.

**Comment by lbross** [comment]
This is done. The data source description and year are items in the desktop_settings.yaml file on basins so that they can be updated when the year changes without having to update the code. Users will need to download a new copy of the settings file or update this item in their local settings file. 

We are printing 'No stream flow data' for AOI's that do not have streamflow data for any reason. This could be that they couldn't download the .csv, that the AOI is missing from the .csv, or that there is no value for the AOI in the .csv, or an another error occurred. More details about why the streamflow is missing can be found in the program log.

**Comment by lbross** [comment]
I am testing the add-in on CS3 and realized that with the current design, BAGIS-PRO cannot download the streamflow .csv file from the NRCS portal unless it is logged into the portal which (I think) requires a user name and password. Is this an acceptable design? If not, I will need to look into alternatives.

**Comment by jdduh** [comment]
I'm not sure if NRCS will use named user license for ArcGIS Pro. If they go that route, then all NRCS ArcGIS Pro users must log on to ArcGIS Online to use ArcGIS Pro. Let's keep the current design for now. I will check with NWCC folks and get back to you.

**Comment by lbross** [comment]
I refined the code around communications with the NRCS Portal so it should be more robust. Also I found that Pro will not download the file if a file of the same name exists in the download directory. I delete the file before trying to download every time but we could add some sort of versioning if we want. Probably the easiest way would be to add a column to the spreadsheet with a version number. Or we could experiment with updating one of the item properties on the portal?

I had to rewrite the code that reads the values from the .csv file. I had used an OleDbConnection library to read the spreadsheet as a database table, but found that this requires that the MS Access runtime be installed on the computer. BioSum uses this so my laptop had it. CS3 did not. This is an old library that we don't want to be dependent on. The code now uses a text parser to read the .csv file. This runs fine on CS3 with no required additional components.

**Comment by jdduh** [comment]
Per Gus's comment: "It is important to note that both the precipitation and runoff need to be in the same units for the ratio to be computed properly.  My suggestion would be to convert the basin total precipitation to kaf (thousands of acre feet) (I think this is already done for the table output) and then divide by the annual runoff from the .csv (thousands of acre feet).  Then multiply by 100 to express as %."

**Comment by lbross** [comment]
Can we confirm the calculation for Annual Runoff Ratio. Here is the calculation for example AOI Elk R nr Milner:
1. Retrieve the basin total precipitation from the PRISM tab of the charts/tables spreadsheet. Sum the VOL_ACRE_FT for all zones. For this example that value is 895975.12. (Note that we may want to allow the analyst to suggest a custom date range for the PRISM tab in the future, so this value may not always be the ANNUAL basin total precipitation).
2. Divide by the annual runoff from the .csv (381.613) then multiply by 100. This results in a value of 234786.32 which does not seem like a valid %? I tried dividing the sum on the spreadsheet by 1000 to get kaf, but this results in 234.79 which still seems too high?

Do we want to add the % sign to the title page?

**Comment by jdduh** [comment]
The runoff data in the CSV has a unit of kaf (thousands of acre feet). This probably was the issue. Please divide the 895975.12 acre feet by 1000 to get kaf. You should be able to get the correct result then.

**Comment by lbross** [comment]
If I divide the 895975.12 acre feet by 1000 but use the annual runoff from the .csv as supplied (381.613) as the divisor and multiply by 100, I get 234.79 which still does not seem like a valid percent. Should I not be multiplying by 100?

**Comment by jdduh** [comment]
The equation was wrong! Here is the correct one. Make sure to convert the numbers to the same unit (kaf in CSV, af in AOI). 1 kaf = 1000 af.

Runoff Ratio = Annual Runoff from CSV (kaf)/Basin Total Average Annual Precipitation from AOI (kaf) x 100%

**Comment by lbross** [comment]
This seems right. I am going to walk through the equation using the example AOI.
1. The numerator is the value from the CSV with no changes; it is already in KAF: 381.613
2. The denominator is the total of the values in the VOL_ACRE_FT column in the precipitation representation table
3. To convert the total to KAF we divide the total by 1000: 895.97512
4. Our annual runoff ratio then is 381.613/895.97512 * 100: 42.5698324

Display questions: Should the runoff ratio be rounded to 2 decimal places? Do we need to add a % sign to the title page or is calling it a ratio good enough?

**Comment by jdduh** [comment]
Please round the value to 2 decimal places and add % sign to either the variable name (i.e., Annual runoff ratio (%)) or the number (i.e., 42.57%).

**Comment by jdduh** [comment]
The annual runoff averages CSV file on NRCS AGOL is updated with new fields and field names.
The original Average_kac_ft is renamed to Average_kac_ft_1981_2010. 
The new fields are: Average_kac_ft_1991_2020 and Number_of_Observations_1991_2020.

**Comment by lbross** [comment]
This is done and ready for deployment. The fields in the bagis-h-settings.json still need to be documented, but these 4 settings apply to this calculation:
AnnualRunoffItemId: This is assigned by AGOL when an item is uploaded. This value doesn't change if the item is just updated.
AnnualRunoffDataField: The name of the field we query in the .csv file to get the value. New with this implementation.
AnnualRunoffDataDescr and AnnualRunoffDataYear: These values are used to compose the description of the annual runoff file in the data sources
