### ISSUE TITLE
Basin Analysis Report - Monthly SWE Change (Delta) Maps

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#6]
Produce a series of monthly SWE delta maps (averaged first day of month minus the averaged first day of the previous month) from the SNODAS maps to indicate when and where basins tend to accumulate or ablate snow.
Map captions: These maps indicate when and where basins tend to accumulate or ablate snow.

The maps are based on the averaged first day of the month (e.g., Dec 1st minus Nov 1st) SNODAS SWE data, to include the followings: Dec-Nov, Jan-Dec, Feb-Jan, Mar-Feb, Apr-Mar, May-Apr, Jun-May, Jul-Jun. Consider using Red-Blue continuous symbology to show accumulation (blue) and ablation (red).

CSAR server already has some of the averaged first day of the month SWE image services. Geoffrey will compile and add Nov 1st and July 1st image services to the server.

**Comment by lbross** [comment]
I assume that the 'averaged first day of month' are the existing SWE web services that we are already using? Does this series of maps replace the existing SWE maps? Or is it a new series? If a new series, do we want to add the original format SWE maps for Nov 1st and July 1st?

I will do this manually and then provide a series of maps for your review before coding.

**Comment by lbross** [comment]
See attached samples for Jan - Dec, Apr - Mar, and Jun - May. I tried it with transparency and the hillshade but it made the change less clear. I'd like it if you could 0 as the middle of the stretch symbology but couldn't find a way to do that in Pro. I left the depth units on. Agree? Any other suggestions?
[jan_dec_swe_delta.pdf](https://github.com/PSU-CSAR/bagis-pro/files/6213562/jan_dec_swe_delta.pdf)
[apr_mar_swe_delta.pdf](https://github.com/PSU-CSAR/bagis-pro/files/6213564/apr_mar_swe_delta.pdf)
[jun_may_swe_delta.pdf](https://github.com/PSU-CSAR/bagis-pro/files/6213565/jun_may_swe_delta.pdf)

**Comment by jdduh** [comment]
July 1st and November 1st SNODAS SWE webservices are online. See: http://webservices.geog.pdx.edu/arcgis/rest/services/DAILY_SWE_NORMALS

Except for May, June, and July 1st layers, all the other layers are now updated with the data for the 2021 water year (began on October 1, 2020 and ended on September 30, 2021).

**Comment by lbross** [comment]
The current description for this data source is "SWE Data Source - Averaged daily SNOw Data Assimilation System (SNODAS) Snow Water Equivalent (SWE) from 2004 to 2019 data". We have one description for all of the SWE layers. Please provide me the text if you would like me to update it.

**Comment by jdduh** [comment]
Is it possible to get the description from the webservice (e.g., from the January 1st layer)? If this is too troublesome, then probably we can say something like: ""SWE Data Source - Averaged daily SNOw Data Assimilation System (SNODAS) Snow Water Equivalent (SWE) from 2004 to current water year data. See https://www.nohrsc.noaa.gov/ for more information."

**Comment by lbross** [comment]
Retrieving this information at the webservice level would require some significant re-architecting. I don't know that it is worth it in this case. Your backup suggestion should work well. I will update.

**Comment by jdduh** [comment]
Sounds good.

**Comment by jdduh** [comment]
NWCC is interesting in sharing the delta maps/GIS layers (for the whole US). We might need to create theses delta maps as image services. The could change the work flow of the current implementation (i.e., the delta maps are generated within the AOI, not for the complete SWE dataset).

**Comment by jdduh** [comment]
Here is another comment on the symbology of the delta map - the blue-red dichotomy symbology needs to be centered at 0. All negative values are in red and all positive values are in blue.

**Comment by lbross** [comment]
Per our conversation, Pro does not provide the option of centering a continuous color ramp at 0. As a workaround, I set the min and the max to the greater of the absolute min max values. Min is set to the negative value. This should have the effect of centering the symbology at 0.

Per Gus' request, I will add 'Source:  SNODAS' to the existing units textbox. This will either be in 2 lines (preferable) or separated by a comma.

**Comment by jdduh** [comment]
The SWE delta maps don't have the hillshade layer as the background. Please follow the same hillshade setting used for the SWE maps to display the SWE delta maps. NWCC needs the maps to show 0 (zero) from other none zero cells.

**Comment by lbross** [comment]
These maps also don't have the river layer like the SWE maps do. Do you want me to add that?

**Comment by jdduh** [comment]
Yes, please add the river layer to the maps. The symbology looks good and is effective to show cells with a 0 value.

**Comment by lbross** [comment]
I am stuck on this symbology. I figured out how to create a custom color ramp with the colors that you requested, but it doesn't apply the same across all the months because the number of rows (intervals) in the zonal raster differ between months. To make sure I didn't have a mistake in the custom color ramp, I found a built-in color ramp that clearly shows the differences between zones. I posted a sample for Marias to the nwcc portal so you can see what I'm talking about. In this example, I am regenerating the legend with each map so the colors are re-applied.
I think it would work if I could create the legend and colorizer once and share it across all the maps. I could query and find the month with the most intervals and use that, but it wouldn't necessarily have all of the intervals. And Pro doesn't have many hooks to go into and modify the colorizer.

**Comment by jdduh** [comment]
It might work if you use the classify symbology with the custom color ramp on the original SWE rasters (instead of on the zoned rasters).

**Comment by lbross** [comment]
I think I may have finally gotten it right. Please take a look at the Marias sample on the NWCC portal. This is a combination of using a custom color ramp and manipulating the json values in a CIMRasterClassifyColorizer. I am using the symbology on the original SWE rasters so no longer need to create zoned rasters.

**Comment by jdduh** [comment]
A few comments:
1. change the legend labels on SWE maps from 0 - 0.00001 to 0 and 0.00001 - 0.5 to 0 - 0.5.
2. Similarly, change the legend labels on Delta maps. Replace 0.000001 with 0. If that results 0 - 0, then change it to just 0.
3. It's fairly easy to spot the 0 on the delta maps, but no so easy on the SWE map. We might need to tweak the color further.

**Comment by lbross** [comment]
I updated the formatting for the labels in the legend to make them consistent and also to implement your requests. I implemented the custom color ramp that you requested for the SWE DELTA map and it does look better. I posted 3 samples to the NWCC portal.

**Comment by jdduh** [comment]
The color for 0 is white, but it looks like grey in the legend. Also, the color of light and dark blue need to be switched. The color design idea is that light brown (most dry), dark brown (less dry), dark blue (less wet), light blue (most wet). Also, can you verify the data in the image below. It shows that most part of the AOI is 0-0.5 and 0 is between the 0-0.5 and 0.5-4.5 zones. That looks odd.
 
![image](https://user-images.githubusercontent.com/11510708/140426946-5ce782dd-42c8-428f-8a1d-0d4bf0533e16.png)

**Comment by jdduh** [comment]
Is it because that you still have 0 as transparent?

**Comment by lbross** [comment]
I switched the blues; Those were implemented in the incorrect order. The symbology for the November map(s) is behaving strangely. I was able to replicate with the Animas AOI. It seems that there is a bug in the software that doesn't apply the color ramp correctly if the lowest value (0) is not in the initial map load. We were using May for the initial load which often didn't have any 0 cells. I switched this to July, which should always have the lowest value, and it appears to be working correctly. The upper bound doesn't seem to have any problem. I posted a new set of maps for Little Bighorn to the NRCS Portal.

The Classify symbology doesn't give you the option to set 0 as transparent.

I agree that its hard to tell the difference between the light grey and white. I will switch the light grey to light green and post some new examples.

**Comment by lbross** [comment]
Change 0 to green for delta maps

**Comment by lbross** [comment]
Change title(s) from 'AVERAGE NOVEMBER SWE DELTA' to 'SNODAS MEAN NOVEMBER SWE DELTA'

**Comment by jdduh** [comment]
This issue is related to both the SWE and SWE delta maps. You can find a copy of this AOI (09286700_UT_USGS_04112022) in the C:\AOIs\Debug folder on CS3.

Question: do we convert SWE from mm to inch in the batch tool? This issue might be related to the unit conversion.

Issue:
The mean SWE map shows that there was no snow pack in the Nov 1 and Dec 1 mean SWE data, which is probably not possible for this AOI.

![image](https://user-images.githubusercontent.com/11510708/164584892-7a64c057-551d-491e-aada-f9c712b60b6e.png)

However, the delta map tells a very different story.

![image](https://user-images.githubusercontent.com/11510708/164584999-bd07aa5e-cf2b-41db-9ea7-a3756990797f.png)

When I checked the source SWE rasters clipped to the AOI and the calculated delta rasters, their values don't match what's indicated in the legend.

**Comment by lbross** [comment]
Yes. We are converting from mm to inches when displaying these maps. I will look into this. My hunch is that it was introduced when we went to the multi-pane maps sharing a legend/symbology as they appeared to be correct under the old version.

**Comment by lbross** [comment]
This seems to be a problem when there are no cells with values in the lowest classifications. For example, November, December, and January all have positive values. I am going to try calculating the minimum value for each layer and removing the smaller classifications with no members to see if that helps. I hope that ArcGIS keeps the same colors for the remaining categories.

**Comment by jdduh** [comment]
Here are the screenshots of the symbology issue associated with the seasonal precipitation contribution map (see #7). The symbology for Mar, Apr, & Map map is incorrect.
![image](https://user-images.githubusercontent.com/11510708/165397151-0e687599-c314-40c8-a373-035e45d83288.png)

The correct map should look like:

![image](https://user-images.githubusercontent.com/11510708/165397235-c88a190f-c4fd-40f7-90db-ea059c139f9f.png)

**Comment by lbross** [comment]
I think this is done. Please see updated map on CS3 at C:\AOIs\Debug\09286700_UT_USGS_04112022\maps_publish. Fixing one map fixed them all. I also updated the seasonal precip map as requested in issue #7. That should be reflected in this new sample.
