### ISSUE TITLE
Basin Analysis Report - Seasonal Precipitation Contribution Maps

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#7]
Show a series of seasonal precipitation maps and their % of annual precipitation maps. We currently have calendar quarterly PRISM precipitation data (Q1, Q2, Q3, and Q4) on the server. We need to compile new 'seasonal' quarterly PRISM precipitation data.
- SQ1: Dec, Jan, Feb
- SQ2: Mar, Apr, May
- SQ3: Jun, Jul, Aug
- SQ4: Sep, Oct, Nov

SQ1_Precip_Contribution = SQ1/Annual x 100%

**Comment by lbross** [comment]
Will @jdduh be adding new image services for these 'seasonal quarters'? Or do we create the layers on the client side by adding values from the existing monthly maps?

Any suggestions for symbology? Again, I will do this manually and provide samples for your review before coding.

We are adding a lot of new maps. Do we want to start organizing the view maps buttons in ArcGIS into categories?

**Comment by jdduh** [comment]
The seasonal quarterly precipitation image services are online now. See:

**Comment by lbross** [comment]
Can you clarify if this is 4 new maps or 8 new maps? Are there 2 sets of maps (quarterly PRISM precipitation data and % of annual precipitation) ? Or just the 4 quarterly % of annual precipitation?

**Comment by lbross** [comment]
Clip seasonal precip when we clip other PRISM layers. Use annual layer for total. Only 4 new maps for precipitation contribution. Use the precipitation color ramp. Min is 0, Max is 100 because these are percentages.

**Comment by lbross** [comment]
See attached sample. I will need to fix the values in the legend when I implement. They should be 0 to 100 as you requested. I'm not sure about the symbology. I have a feeling most of the maps will be in the yellow/orange range (< 25%). Let me know what you think.
[seasonal_precip.pdf](https://github.com/PSU-CSAR/bagis-pro/files/7024291/seasonal_precip.pdf)

**Comment by lbross** [comment]
Switch to using calculated intervals like we do for SWE Delta maps. Center at 23-27% and make 3 equal intervals on either side of that. Consider making the center larger if significant departure from 25% is not clearly visible. Share color ramp with SWE Delta maps where the center interval is green. Symbology for SWE Delta maps may change.

**Comment by lbross** [comment]
Change color ramp to share SWE Delta map

**Comment by jdduh** [comment]
Some texts on this map need to be updated.
1. The lower right map should be SEP, OCT, & NOV
2. Remove the depth units = inches. The map unit is %. We need to put that information either in the legend (e.g., Precip Contribution %) or replace the label with "Data Units = %"
