### ISSUE TITLE
Basin Analysis Report - Federal none-wilderness land

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#9]
Use the AGBUR to symbolize the map. Make sure that wilderness is clearly separated from other federal land.
Geoffrey will update the NRCS federal_lands service.
1. Add wilderness as the prefix to the AGBUR (this might involve changing the field definition because AGBUR doesn't have enough length to store all the texts).
2. Label other none-federal public land as "None-federal public" in the AGBUR field.

**Comment by lbross** [comment]
What does "clearly separated" mean? Just the change to the AGBUR values in the webservice?

**Comment by jdduh** [comment]
Currently AGBUR lumps wilderness and other none wilderness federal land.

**Comment by lbross** [comment]
'Federal Non-Wilderness Land' map - Underlying data has changed; Reclip; Web service has been updated; Change map title in application
'Public Land Ownership' map - Update title

**Comment by lbross** [comment]
Do we need to filter the BAGIS_Public_Land layer where called ‘Public_ = 1 for this map? We are applying this filter with the 'Federal Non-Wilderness Land' map.

**Comment by jdduh** [comment]
Yes, we still need to rely on the values in the 'Public' attribute field. I have changed wilderness's value to 0. We might need to rename the field name to prevent confusion. How about 'Suitable_Public'?

**Comment by lbross** [comment]
The new field name sounds fine. Just let me know when you change it and I will update the code.

**Comment by lbross** [comment]
Attached are samples of the two maps. I hope I got all the changes. I know that the value in the AGBUR will be changing but that shouldn't effect the code.
[map_public_land_ownership.pdf](https://github.com/PSU-CSAR/bagis-pro/files/6111023/map_public_land_ownership.pdf)
[map_public_land_zones.pdf](https://github.com/PSU-CSAR/bagis-pro/files/6111024/map_public_land_zones.pdf)

**Comment by lbross** [comment]
Why does the land ownership not have the stripes while the land zones map does? Color?

**Comment by jdduh** [comment]
The attribute update is completed. The values of federal wilderness land in the AGBUR field is now labeled with "Wilderness" as a prefix to the government agency's abbreviated name.

https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/BAGIS_Public_Land/FeatureServer

**Comment by lbross** [comment]
We discussed earlier renaming the 'Public' to 'Suitable_Public'. It appears this field still has the same name which is fine with me, but I want to make sure we didn't miss a requirement.
I am not seeing any polygons on our public lands map with the 'Wilderness' prefix, but this is expected, right? I'm only including non-wilderness polygons where 'Public' = 1 so I will never see this change.

**Comment by jdduh** [comment]
I have added the "Suitable_Public" field and copied the data from the "Public" field. Please select only the polygons with a value of 1 in the Suitable_Public field to generate the "Federal non-wilderness land" map. For the "Public Land Ownership" map, please use all polygons (which also include wilderness and non-federal public lands).

**Comment by lbross** [comment]
That makes a lot more sense. I made the code changes to support. Thanks!

**Comment by lbross** [comment]
Why is public land ownership map missing from the current watershed report? @jdduh to redesign the site analysis maps that include land ownership, federal non-wilderness lands, and roads.

**Comment by lbross** [comment]
Add roads layer to federal non-wilderness lands map. Use color and thickness that is visible with red transparent layer. Not black. Maybe dark brown?
'Access Roads and Federal Non-Wilderness Lands' new title.
Stop including 'Proximity to Access Roads' map but include the buffer layer on Potential Site Location maps.

Area Below Treeline: Replace with 'Forested Land Cover' map. Use NLCD layer as source. Set deciduous forest, evergreen forest, and mixed forest to transparent red. Use this as an element of the potential site location map.

**Comment by jdduh** [comment]
For potential site locations analysis, now we need to include Indian Reservation areas as potential locations. There is a separate Indian Reservation GIS dataset that needs to be merged with the Federal Land GISs GIS layer. I will change the "Suitable_Public" field name to "Suitable_Areas" because Indian Reservation areas are not public. I will post here when the updated GIS layer is available.

**Comment by lbross** [comment]
If we use the NLCD layer for the 'Forested Land Cover' map, do we still need to clip the landfire vegetation layer (LF_us_140evt)
? I don't think we're using it for anything else.

**Comment by jdduh** [comment]
That's correct. The landfire layer won't be used in the watershed report. Please don't clip it to the AOI. BAGIS-P still uses it for parameterization. BAGIS-P users will have to clip it using the Data Management tool.

**Comment by lbross** [comment]
OK. I will remove landfire from the BAGIS-PRO interface and data sources list on the title page.

**Comment by jdduh** [comment]
A new Public_and_Tribal_Lands feature layer service is published on NRCS ArcGIS Online. Please use this layer to replace the original BAGIS_Public_Land layer. The new layer has the same AGBUR field and a new field, called Suitable. Use suitable = 1 for suitable snotel site selection.
https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/Public_and_Tribal_Lands/FeatureServer

**Comment by jdduh** [comment]
We need to create a standard symbol set for different land ownership types. I notice that the land ownership maps (page 29) of two AOIs that have the same land ownership look completely different (colorwise).

**Comment by lbross** [comment]
I can do this. We will use the same process (layer file stored on AGOL) that we did for land cover. Do you have any preference for color scheme?

**Comment by jdduh** [comment]
No preference of the color scheme. Here is a complete list of AGBUR values. Will the map legend just shows the ownership types that are present on the map (i.e., in the AOI)? Or they show every possible values? I have the same question for the NLCD land cover map legend.

AIR: American Indian Reservation
ARS: Agricultural Research Service
BLM: Bureau of Land Management
BPA: Bonneville Power Administration
DOD: Department of Defense
DOE: Department of Energy
FWS: U.S. Fish and Wildlife Service
NOAA: National Oceanic and Atmospheric Administration
NPS: National Park Service
NRCS: Natural Resources Conservation Service
TVA: Tennessee Valley Authority
USACE: Army Corps of Engineers
USBR: Bureau of Reclamation
USFS: Forest Service
Wilderness BLM
Wilderness FS
Wilderness FWS
Wilderness NPS
Non-Federal Public

**Comment by lbross** [comment]
The only way I know how to do this is to let ArcGIS Pro build the symbology so that I can export it to a layer file. I added the Public and Tribal Lands service to Pro and then generated unique values symbology that covers all of the possible AGBUR values. When applying a layer, it seems that all the possible values show up in the legend. This is true for NLCD land cover too. I don't know if there is a way to regenerate the legend with only the present values. I haven't found one. This legend is long so I will need to add it to the processing that makes the fonts smaller (elevation and NLCD zones).

Attached is a sample of what I have so far.
[Land Ownership.pdf](https://github.com/PSU-CSAR/bagis-pro/files/8483726/Land.Ownership.pdf)

**Comment by jdduh** [comment]
This actually makes the map legend less effective. The original map was easier to tell what is what than the new one. How about not making any change? I think we have a good reason to justify that the map color might be different from AOI to AOI until we can figure out a way to trim the legend items. Have you set a particular colorramp when displaying the land ownership map?

**Comment by lbross** [comment]
We have been using the "ArcGIS Colors", "Basic Random" color ramp when displaying the land ownership map. I will spend some more time to see if there is a way to remove values that are not on the map. I won't spend too much time.

**Comment by jdduh** [comment]
NWCC shared a way to remove values that are not on the map. When you "Apply Symbology From Layer", you can set the Update Symbology Ranges by Data parameter to "Update ranges." This will remove all symbols that are not on the map. If this is a feasible solution, then please apply this change for both the land ownership map and the land cover map.

**Comment by jdduh** [comment]
Here is the layer file with the symbols for the land ownership map. Please rename the file extension name to .lyrx.

[Public_and_Tribal_Lands.txt](https://github.com/PSU-CSAR/bagis-pro/files/8543174/Public_and_Tribal_Lands.txt)

**Comment by lbross** [comment]
You can play around with this tool and see if you can get it to work. I cannot. It is a Geoprocessing Tool called 'Apply Symbology From Layer'. When I set this parameter to "update ranges", it changes all the colors which seems to defeat the point of using a layer file to have consistent symbology. I have tried all the options with the same results. If you want to try, the nlcd_land_cover.lyrx should be in your AppData/Roaming/BAGIS folder.
Do you still want me to implement the layer file for the land ownership map even if it has to show all the categories, including those not on the map, to be consistent?

**Comment by jdduh** [comment]
Please reclip the land ownership data. The new data has a different set of AGBUR values from the old one. That might cause the color to change. We will keep the current legend if this doesn't work.

**Comment by jdduh** [comment]
I will create a new NLCD layer file that's based on the value field. The current layer file probably doesn't support the Apply Symbology From Layer tool.

**Comment by jdduh** [comment]
It seems that the Apply Symbology From Layer tool doesn't work as intended for raster data (i.e., NLCD land cover). It works normally on vector data (i.e., public and tribal land layer). As least we can make all land ownership maps the same.

**Comment by lbross** [comment]
After reclipping the land ownership data, the 'Apply Symbology From Layer' GP tool with the Update Ranges option enabled appears to be working as desired. I will plan on implementing this for the Land Ownership map. I assume there are no changes for the Land Cover map as this tool doesn't work for raster data?
